<?php

/**
 * Implements hook_permission().
 */
function unitegallery_ui_permission() {
  $permission = array();

  $permission['administer unitegallery'] = array(
    'title' => t('Administer Unite Gallery'),
    'description' => t('Perform administration tasks for unite gallery.'),
  );

  return $permission;
}

/**
 * Implements hook_menu().
 */
function unitegallery_ui_menu() {
  $items = array();

  $items['admin/config/user-interface/unitegallery'] = array(
    'title' => t('Unite Gallery'),
    'page callback' => 'unitegallery_settings_list',
    'access arguments' => array('administer unitegallery'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/user-interface/unitegallery/%'] = array(
    'title' => t('Unite Gallery Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('unitegallery_settings_form', 4),
    'access arguments' => array('administer unitegallery'),
  );

  return $items;
}

function unitegallery_settings_list() {
  $gallery_types = _unitegallery_media_types();

  foreach ($gallery_types as $typek => $typev) {
    $items[] = l(t($typev), 'admin/config/user-interface/unitegallery/' . $typek);
  }

  return theme('item_list', array('items' => $items));
}

function unitegallery_settings_form($form, &$form_state, $type) {
  $gallery_types = _unitegallery_media_types();

  if (!isset($gallery_types[$type])) {
    drupal_not_found();
    exit;
  }

  drupal_set_title(t('Unite Gallery @title Settings', array('@title' => $gallery_types[$type])));

  $form['#attached']['css'] = array(drupal_get_path('module', 'unitegallery') .'/theme/unitegallery_ui.css');
  $form['back']['#markup'] = l(t('Go back'), 'admin/config/user-interface/unitegallery');

  $js_config = unitegallery_js_config_default($type);
  $form['config'] = array(
    '#type'        => 'textarea',
    '#title'       => t('@title configuration', array('@title' => $gallery_types[$type])),
    '#default_value' => variable_get('unitegallery_js_config_' . $type, drupal_json_encode($js_config)),
    '#description' => t('Sample format: {"gallery_width":"100%","gallery_height":500,"slider_control_zoom":false,"thumb_width":122,"thumb_height":80}
    ')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save configuration')
  );

  module_load_include('inc', 'unitegallery', 'includes/unitegallery_ui_default.settings');
  if ($options = unitegallery_settings_default()) {
    $data = array();
    $data['header'] = array(
      'name'        => t('Config'),
      'value'       => t('Value'),
      'description' => t('Description'),
    );

    foreach ($options as $configk => $configv) {
      $data['rows'] = $configv['options'];
      $form[$type][$configk] = array(
        '#type' => 'fieldset',
        '#title' => t($configv['title']),
        '#collapsible' => TRUE,
        '#value' => theme('table', array('header' => $data['header'],'rows' => $data['rows'])),
        '#collapsed' => TRUE,
      );
    }
  }

  return $form;
}

function unitegallery_settings_form_submit(&$form, &$form_state) {
  variable_set('unitegallery_js_config_' . $form_state['build_info']['args'][0], $form_state['values']['config']);
  drupal_set_message(t('The configuration options have been saved.'));
}